# Generated by Django 4.0.10 on 2023-09-07 18:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_publicacione_delete_publicacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacione',
            new_name='Publicacion',
        ),
    ]
